method: bayes
metric:
    goal: minimize
    name: test_loss_avg
parameters:
    model:
        value: 2
    batch_size:
        values: [64]
    d_model:
        value: 23
    dff:
        values: [128, 256]
    dropout:
        distribution: uniform
        min: 0.05
        max: 0.15
    l_win:
        distribution: int_uniform
        min: 115
        max: 125
    lr: 
        distribution: log_uniform
        min: -7.5
        max: -5.5
    n_epochs: 
        distribution: int_uniform
        min: 60
        max: 120
    n_head: 
        values: [1, 23]
    num_layers: 
        distribution: int_uniform
        min: 1
        max: 3
    kernel_size: 
        distribution: int_uniform
        min: 3
        max: 7
    weight_decay:
        distribution: log_uniform
        min: -7
        max: -6
    num_workers: 
        values: [2]
